export const STATS = [
  { value: "14,000+", label: "Registered health facilities" },
  { value: "47", label: "Counties covered nationwide" },
  { value: "Real-time", label: "Route and distance calculation" },
  { value: "100% Free", label: "Open access care locator" },
];

export const FACILITIES = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.80700922760637, -1.301141731273861],
      },
      properties: {
        phone: "020-2726300",
        email: "knhadmin@knh.or.ke",
        name: "Kenyatta National Hospital",
        address: "Hospital Road",
        mailingAddress: "P.O Box 20723 - 00202, Nairobi",
        city: "Nairobi",
        country: "Kenya",
        postalCode: "00202",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.80342399557637, -1.308925446606103],
      },
      properties: {
        phone: "020-2724712",
        name: "Mbagathi County Hospital",
        address: "Off Mbagathi Road",
        mailingAddress: "P.O. Box 40205, Nairobi",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.80482, -1.3104],
        // coordinates: [36.80449853413977, -1.3108813422663772],
      },
      properties: {
        phone: "020-2731634",
        email: "publicaffairs@mod.go.ke",
        name: "Kenya Defense Forces Memorial Hospital",
        address: "Nyayo Highrise Mbagathi Way",
        mailingAddress: "P O Box 40668 – 00100, Nairobi",
        city: "Nairobi",
        country: "Kenya",
        postalCode: "00100",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.898979866740454, -1.273794475031693],
      },
      properties: {
        phone: "020-8022676",
        email: "info@mamalucykibakihospital.or.ke",
        name: "Mama Lucy Kibaki Hospital",
        address: "Kangundo Road Umoja II",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.84546656674033, -1.280471127894011],
      },
      properties: {
        phone: "0778564272",
        name: "Pumwani Maternity Hospital",
        address: "Pumwani, Nairobi",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.84655459557629, -1.260549542755912],
      },
      properties: {
        phone: "020-2391431",
        email: "matharirefferal@gmail.com",
        name: "Mathari National & Teaching Hospital",
        address: "Thika Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.79410570828493, -1.2880442556649923],
      },
      properties: {
        phone: "020-2726336",
        name: "National Spinal Injury Referral Hospital",
        address: "Rose Ave, Kilimani",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.80462576938572, -1.2965269902104213],
      },
      properties: {
        phone: "020-2845000",
        email: "hosp@nbihosp.org",
        name: "The Nairobi Hospital",
        address: "Argwings Kodhek Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.79607519538338, -1.2937005464919717],
      },
      properties: {
        phone: "(+254) 709-667-000",
        email: "info@nwch.co.ke",
        name: "Nairobi Women's Hospital - Hurlingham",
        address: "Argwings Kodhek Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        level: 4,
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.825884492577664, -1.3066884481056296],
      },
      properties: {
        phone: "+254730600000",
        email: "enquiry@nairobiwesthospital.com",
        name: "The Nairobi West Hospital",
        address: "Gandhi Ave, Nairobi West",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.83171331841077, -1.2557353381754701],
      },
      properties: {
        phone: "+254730645005",
        email: "info@gerties.org",
        name: "Gertrude’s Children’s Hospital",
        address: "Muthaiga Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.83440951534271, -1.3073582166821127],
      },
      properties: {
        phone: "020-6903000",
        email: "infom@materkenya.com",
        name: "The Mater Hospital",
        address: "Marikani Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.915833, -1.175833],
      },
      properties: {
        phone: "0800721038",
        name: "Kenyatta University Teaching, Referral and Research Hospital",
        address: "Northern Bypass",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.82367743236183, -1.2622706461173347],
      },
      properties: {
        phone: "020-3662856",
        name: "Aga Khan University Hospital",
        address: "Third Parklands Avenue",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.81165811994607, -1.2647112690993019],
      },
      properties: {
        phone: "0111000600",
        name: "M.P Shah Hospital",
        address: "Shivachi Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.82843225562809, -1.3137082658596146],
      },
      properties: {
        phone: "020-5145300",
        name: "Nairobi South Hospital",
        address: "Muhoho Ave",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.817613823573346, -1.264756809390176],
      },
      properties: {
        phone: "0711060000",
        name: "Avenue Hospital",
        address: "First Parklands Avenue",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.7977521050752, -1.2985284746379429],
      },
      properties: {
        phone: "0711043000",
        name: "Coptic Mission Hospital",
        address: "Ngong Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.72617295173464, -1.3359897644859455],
      },
      properties: {
        phone: "020-6613000",
        email: "info@karenhospital.org",
        name: "The Karen Hospital",
        address: "Langata Rd",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.71748794899137, -1.3245440214803061],
      },
      properties: {
        phone: "020-2025714",
        name: "KTTID Dispensary",
        address: "Karen Boyani Rd",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.69068844380261, -1.310929747548302],
      },
      properties: {
        phone: "020-3883137",
        name: "St. Odilia's Dispensary",
        address: "Windy Ridge rd",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.72594750232242, -1.3592472051648008],
      },
      properties: {
        phone: "020-2013647",
        email: "cmiacotrhq@wananchi.com",
        name: "CMIA Grace Children's Centre Dispensary",
        address: "Off Maasai West Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.728580313367644, -1.3652678655941561],
      },
      properties: {
        phone: "020-2430127",
        email: "coopcoll@cooperative.ac.ke",
        name: "The Co-Operative University College of Kenya Dispe",
        address: "Maasai Rd, Off Ushirika Rd",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.703760094272766, -1.3170637812939543],
        // coordinates: [36.70568263224418, -1.321059122415678],
      },
      properties: {
        name: "Karen Health Centre",
        address: "Dagoretti Road",
        mailingAddress: "P.O Box 30108 - 00100, Nairobi",
        postalCode: "00100",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.76907928849926, -1.3365676081148097],
      },
      properties: {
        phone: "020-891801",
        email: "bomas@africaonline.co.ke",
        name: "Bomas of Kenya Dispensary",
        address: "Off Langata Rd",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.75736356371778, -1.352575662872374],
      },
      properties: {
        name: "Catholic University Dispensary",
        address: "Bogani East Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.7269284762475, -1.3396440554810973],
      },
      properties: {
        phone: "020-3884365",
        email: "cottolengochildren@gmail.com",
        name: "Cotolengo Centre",
        address: "Off Langata Rd",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.76578108048439, -1.379066104465738],
      },
      properties: {
        phone: "020-2071391",
        email: "principal@mmu.ac.ke",
        name: "Multi Media University Dispensary",
        address: "Magadi Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.765253884620144, -1.343778907083364],
      },
      properties: {
        phone: "0721425089",
        name: "The Nairobi Hospital (Galleria), Outpatient Centre",
        address: "Galleria Mall, Magadi Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.89072675450932, -1.3289154394895584],
      },
      properties: {
        phone: "0721425089",
        name: "The Nairobi Hospital (Southfield), Outpatient Centre",
        address: "North Airport Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.7745582371447, -1.322820832917922],
      },
      properties: {
        phone: "020-2052720",
        email: "bahatiodemary@yahoo.com",
        name: "St Mary's Mission Hospital",
        address: "Sasuma Crescent",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Hospital",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.789294323999975, -1.3277620818247555],
      },
      properties: {
        phone: "020-604893",
        email: "info@langatahospital.org",
        name: "Langata Hospital",
        address: "Kitengela Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.78898098237847, -1.3149363146894448],
      },
      properties: {
        phone: "0720115087",
        name: "Kibera South Health Centre",
        address: "Kabarnet CL",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: false,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.81476067311332, -1.3094485808796124],
      },
      properties: {
        phone: "020-606155",
        email: "hkoyoson@strathmore.edu",
        name: "Strathmore University Medical Centre",
        address: "KERI ROAD",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [36.779424334055435, -1.320796620263453],
      },
      properties: {
        phone: "0722422955",
        name: "Soweto West Community Clinic",
        address: "Sasuma Road",
        city: "Nairobi",
        country: "Kenya",
        state: "Nairobi City County",
        type: "Health Centre",
        isPrivate: false,
      },
    },
  ],
};
